# Generated by Django 3.1 on 2020-09-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rating_ratingstar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='fess_in_world',
            new_name='fees_in_world',
        ),
    ]
